# https://taskfile.dev

version: '3'

tasks:
  run:
    desc: run shit
    cmds:
      - poetry run python main.py {{.CLI_ARGS}}
    silent: true

  install:
    desc: install shit
    cmds:
      - pip install pipx
      - pipx install poetry
      - poetry install

